server:
  port: 8085
spring:
  application:
    name: appmic-quotingplugins-quotations
  banner:
    location: classpath:/banner.txt
  web:
    resources:
      add-mappings: false
  datasource:
    # Usar variables de entorno para facilitar despliegues (dev/stage/prod)
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quotations_service}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root_password}
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
app:
  endpoints:
    module: "/api/quotations/module"
    module_material: "/api/quotations/module_material"
    quotation: "/api/quotations/quotation"
management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 significa guardar el 100% de las peticiones (para dev está bien)
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # URL del servidor Zipkin en K8s
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true # ¡Vital! Sin esto, devolverá 404 y K8s matará tu pod.
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      ms_material:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        ignore-exceptions:
          - feign.FeignException$NotFound # Indica que el 404 no es un fallo del sistema
      ms_employee:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        ignore-exceptions:
          - feign.FeignException$NotFound # Indica que el 404 no es un fallo del sistema
      ms_customer:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        ignore-exceptions:
          - feign.FeignException$NotFound # Indica que el 404 no es un fallo del sistema
# Configuración específica para el perfil 'dev'
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
config:
  texto: Configurando ambiente de desarrollo
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS:clave-secreta-para-desarrollo-12345}
app:
  external:
    employee-service-url: ${MS_EMPLOYEE_SERVICE_PORT:http://localhost:8082}
    material-service-url: ${MS_MATERIAL_SERVICE_PORT:http://localhost:8083}
    customer-service-url: ${MS_CUSTOMER_SERVICE_PORT:http://localhost:8084}
    employee-service-path: "/api/employees"
    material-service-path: "/api/materials"
    customer-service-path: "/api/customers"
# Configuración específica para el perfil 'prod'
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
logging:
  level:
    org:
      springframework:
        security: INFO
config:
  texto: Configurando ambiente de producción
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS}
app:
  external:
    employee-service-url: ${MS_EMPLOYEE_SERVICE_PORT}
    material-service-url: ${MS_MATERIAL_SERVICE_PORT}
    customer-service-url: ${MS_CUSTOMER_SERVICE_PORT}
    employee-service-path: "/api/employees"
    material-service-path: "/api/materials"
    customer-service-path: "/api/customers"