server:
  port: 8084
spring:
  application:
    name: appmic-quotingplugins-customers
  web:
    resources:
      add-mappings: false
  datasource:
    # Usar variables de entorno para facilitar despliegues (dev/stage/prod)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quoting_db}?currentSchema=${DB_SCHEMA:customers}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root_password}
    hikari:
      maximum-pool-size: 10
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
app:
  endpoints:
    customer: "/api/customers/customer"
management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 significa guardar el 100% de las peticiones (para dev está bien)
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # URL del servidor Zipkin en K8s
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true # ¡Vital! Sin esto, devolverá 404 y K8s matará tu pod.
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
# Configuración específica para el perfil 'dev'
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:customers}
    open-in-view: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
config:
  texto: Configurando ambiente de desarrollo
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS:clave-secreta-para-desarrollo-12345}
app:
  external:
    catalog-service-url: ${MS_CATALOG_ITEM_SERVICE:http://127.0.0.1:8080/api/catalogs}
# Configuración específica para el perfil 'prod'
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:customers}
    open-in-view: true
logging:
  level:
    org:
      springframework:
        security: INFO
config:
  texto: Configurando ambiente de producción
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS}
app:
  external:
    catalog-service-url: ${MS_CATALOG_ITEM_SERVICE}