server:
  port: 8082
spring:
  application:
    name: appmic-quotingplugins-employees
  banner:
    location: classpath:/banner.txt
  web:
    resources:
      add-mappings: false
  datasource:
    # Usar variables de entorno para facilitar despliegues (dev/stage/prod)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quoting_db}?currentSchema=${DB_SCHEMA:employees}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root_password}
    hikari:
      maximum-pool-size: 10
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
app:
  endpoints:
    employee: "/api/employees/employee"
    role: "/api/employees/role"
    user: "/api/employees/user"
management:
  endpoint:
    health:
      probes:
        enabled: true # ¡Vital! Sin esto, devolverá 404 y K8s matará tu pod.
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
# Configuración específica para el perfil 'dev'
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:employees}
    open-in-view: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
config:
  texto: Configurando ambiente de desarrollo
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS:clave-secreta-para-desarrollo-12345}
# Configuración específica para el perfil 'prod'
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:employees}
    open-in-view: false
logging:
  level:
    org:
      springframework:
        security: INFO
config:
  texto: Configurando ambiente de producción
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS}