server:
  port: 8082
spring:
  application:
    name: appmic-quotingplugins-employees
  banner:
    location: classpath:/banner.txt
  web:
    resources:
      add-mappings: false

  datasource:
    # Usar variables de entorno para facilitar despliegues (dev/stage/prod)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quoting_db}?currentSchema=${DB_SCHEMA:employees}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root_password}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # Ajustar en producción a 'valídate' o 'none'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:employees}