server:
  port: 8081
spring:
  application:
    name: appmic-quotingplugins-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: ${MS_AUTH_SERVICE_LB:http://127.0.0.1:9000}
              predicates:
                - Path=/api/auth/**
            - id: catalogs-service
              uri: ${MS_CATALOGS_SERVICE_LB:http://127.0.0.1:8080}
              predicates:
                - Path=/api/catalogs/**
            - id: customers-service
              uri: ${MS_CUSTOMERS_SERVICE_LB:http://127.0.0.1:8084}
              predicates:
                - Path=/api/customers/**
            - id: employees-service
              uri: ${MS_EMPLOYEES_SERVICE_LB:http://127.0.0.1:8082}
              predicates:
                - Path=/api/employees/**
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
# Configuración específica para el perfil 'dev'
---
spring:
  config:
    activate:
      on-profile: dev
config:
  texto: Configurando ambiente de desarrollo gateway
# Configuración específica para el perfil 'prod'
---
spring:
  config:
    activate:
      on-profile: prod
config:
  texto: Configurando ambiente de producción gateway