apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-catalogs
  namespace: dev
data:
  profile_active: "dev"
  port: "8080"
  db_host: "postgres"
  db_port: "5432"
  db_name: "quoting_db"
  db_schema: "catalogs"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-employees
  namespace: dev
data:
  profile_active: "dev"
  ms_catalog_item_service: "http://appmic-quotingplugins-catalogs:8080/api/catalogs"
  port: "8082"
  db_host: "postgres"
  db_port: "5432"
  db_name: "quoting_db"
  db_schema: "employees"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-customers
  namespace: dev
data:
  profile_active: "dev"
  ms_catalog_item_service: "http://appmic-quotingplugins-catalogs:8080/api/catalogs"
  port: "8084"
  db_host: "postgres"
  db_port: "5432"
  db_name: "quoting_db"
  db_schema: "customers"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-auth
  namespace: dev
data:
  profile_active: "dev"
  ms_employee_service: "http://appmic-quotingplugins-employees:8082/api/employees"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-gateway
  namespace: dev
data:
  profile_active: "dev"
  port: "8081"
  ms_auth_service_lb: "http://appmic-quotingplugins-auth:9000"
  ms_customers_service_lb: "http://appmic-quotingplugins-customers:8084"
  ms_catalogs_service_lb: "http://appmic-quotingplugins-catalogs:8080"
  ms_employees_service_lb: "http://appmic-quotingplugins-employees:8082"
  ms_materials_service_lb: "http://appmic-quotingplugins-materials:8083"
  ms_quotations_service_lb: "http://appmic-quotingplugins-quotations:8085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-materials
  namespace: dev
data:
  profile_active: "dev"
  port: "8083"
  ms_catalog_item_service: "http://appmic-quotingplugins-catalogs:8080/api/catalogs"
  db_host: "postgres"
  db_port: "5432"
  db_name: "quoting_db"
  db_schema: "materials"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appmic-quotingplugins-quotations
  namespace: dev
data:
  profile_active: "dev"
  port: "8085"
  ms_employee_item_service: "http://appmic-quotingplugins-employees:8082"
  ms_material_item_service: "http://appmic-quotingplugins-materials:8083"
  ms_customer_item_service: "http://appmic-quotingplugins-customers:8084"
  db_host: "mysql"
  db_port: "3306"
  db_name: "quotations_service"