apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-schemas.sql: |
    CREATE SCHEMA IF NOT EXISTS catalogs;
    CREATE SCHEMA IF NOT EXISTS customers;
    CREATE SCHEMA IF NOT EXISTS employees;