apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-dev
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/dev
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-prod
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/prod
    type: DirectoryOrCreate