apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-catalogs
  namespace: prod
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-employees
  namespace: prod
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-customers
  namespace: prod
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-auth
  namespace: prod
type: Opaque
stringData:
  jwt-signature-quotations: "XyZ-998877-Super-Secure-Hash-Prod-v1"