apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-catalogs
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-employees
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-customers
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-auth
  namespace: dev
type: Opaque
stringData:
  jwt-signature-quotations: "clave-secreta-para-desarrollo-12345"
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-auth
  namespace: prod
type: Opaque
stringData:
  jwt-signature-quotations: "XyZ-998877-Super-Secure-Hash-Prod-v1"