apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-catalogs
  namespace: dev
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-employees
  namespace: dev
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-customers
  namespace: dev
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-auth
  namespace: dev
type: Opaque
stringData:
  jwt-signature-quotations: "appmic-quotingplugins-secret-key"