apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-catalogs
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: appmic-quotingplugins-employees
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cm9vdF9wYXNzd29yZA==