server:
  port: 9000
spring:
  application:
    name: appmic-quotingplugins-auth
  web:
    resources:
      add-mappings: false
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
app:
  endpoints:
    auth: "/api/auth"
management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 significa guardar el 100% de las peticiones (para dev está bien)
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans" # URL del servidor Zipkin en K8s
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
# Configuración específica para el perfil 'dev'
---
spring:
  config:
    activate:
      on-profile: dev
config:
  texto: Configurando ambiente de desarrollo
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS:clave-secreta-para-desarrollo-12345}
app:
  external:
    employee-service-url: ${MS_EMPLOYEE_SERVICE:http://127.0.0.1:8082/api/employees}
# Configuración específica para el perfil 'prod'
---
spring:
  config:
    activate:
      on-profile: prod
config:
  texto: Configurando ambiente de producción
jwt:
  secret: ${JWT_SIGNATURE_QUOTATIONS}
app:
  external:
    employee-service-url: ${MS_EMPLOYEE_SERVICE}