server:
  port: ${PORT:8080}
spring:
  application:
    name: appmic-quotingplugins-catalogs
  web:
    resources:
      add-mappings: false
  datasource:
    # Usar variables de entorno para facilitar despliegues (dev/stage/prod)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quoting_db}?currentSchema=${DB_SCHEMA:catalogs}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root_password}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update # Ajustar en producción a 'valídate' o 'none'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:catalogs}
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:dev}
logging:
  level:
    org:
      springframework:
        security: DEBUG
# Configuration by defecto
---
config:
  texto: Configurando ambiente por defecto
# Configuración específica para el perfil 'dev'
---
spring:
  config:
    activate:
      on-profile: dev
config:
  texto: Configurando ambiente de desarrollo
# Configuración específica para el perfil 'prod'
---
spring:
  config:
    activate:
      on-profile: prod
config:
  texto: Configurando ambiente de producción